name: myapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
    

  cupertino_icons: ^1.0.8
  weather: ^3.1.1
  geolocator: ^9.0.2
  intl: ^0.19.0
  get: ^4.6.6  
  velocity_x: ^4.2.1
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.4
  firebase_storage: ^12.3.1
  cloud_firestore: ^5.5.0
  image_picker: ^1.1.2
  path_provider: ^2.0.15
  flutterfire_cli: ^0.1.1+2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^5.0.0

flutter:
  # The following line ensures that the Material Icons font is included with your application.
  uses-material-design: true

  assets:
    - assets/images/
    - lib/services/category_model.json
   
   
  # Add the assets section here:


  # To add custom fonts to your application, add a fonts section here.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
